### PR TITLE
Remove newline from set(JAVA_AWT_INCLUDE_PATH NotNeeded)

### PR DESCRIPTION
**Pull request by JayjeetAtGithub**

### CODE REVIEW

**Comment by JayjeetAtGithub** [comment]
This is a multi-line test comment
- With GitHub **Markdown** :sparkles:
- Created by [create-or-update-comment][1]
[1]: https://github.com/peter-evans/create-or-update-comment

**Comment by JayjeetAtGithub** [comment]
This is a multi-line test comment
- With GitHub **Markdown** :sparkles:
- Created by [create-or-update-comment][1]
[1]: https://github.com/peter-evans/create-or-update-comment

**Comment by JayjeetAtGithub** [comment]
This is a multi-line test comment
- With GitHub **Markdown** :sparkles:
- Created by [create-or-update-comment][1]
[1]: https://github.com/peter-evans/create-or-update-comment

**Comment by JayjeetAtGithub** [comment]
This is a multi-line test comment
- With GitHub **Markdown** :sparkles:
- Created by [create-or-update-comment][1]
[1]: https://github.com/peter-evans/create-or-update-comment

**Comment by JayjeetAtGithub** [comment]
This is a multi-line test comment
- With GitHub **Markdown** :sparkles:
- Created by [create-or-update-comment][1]
[1]: https://github.com/peter-evans/create-or-update-comment

**Comment by JayjeetAtGithub** [comment]
This is a multi-line test comment
- With GitHub **Markdown** :sparkles:
- Created by [create-or-update-comment][1]
[1]: https://github.com/peter-evans/create-or-update-comment

**Comment by JayjeetAtGithub** [comment]
This is a multi-line test comment
- With GitHub **Markdown** :sparkles:
- Created by [create-or-update-comment][1]
[1]: https://github.com/peter-evans/create-or-update-comment

**Comment by JayjeetAtGithub** [comment]
This is a multi-line test comment
- With GitHub **Markdown** :sparkles:
- Created by [create-or-update-comment][1]
[1]: https://github.com/peter-evans/create-or-update-comment

**Comment by rahul799** [comment]
Build output of commit ac90ba7db02b7a912dfd7776ccd2309ce8b0b7b2
Column Plot
Plot
Row Plot
Plot

**Pull request closed without merging**
